### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by bloodmajik** [JohnCoates/Slate#11]
Showing All Issues
None of your accounts are a member of 'E6QK4MU6LM':  An unexpected error occurred. Xcode cannot find a team matching 'E6QK4MU6LM'.

Showing All Issues
No profiles for 'com.johncoates.camera' were found:  Xcode couldn't find a provisioning profile matching 'com.johncoates.camera'.

Showing All Issues
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

I just needs Pods_slate.framework!

**Comment by JohnCoates** [comment]
Switch your team in project settings, install CocoaPods, run 'pod install'
inside project directory

**Comment by bloodmajik** [comment]
Failed to create provisioning profile. The app ID "com.johncoates.camera"
cannot be registered to your development team. Change your bundle
identifier to a unique string to try again.

No profiles for 'com.johncoates.camera' were found:  Xcode couldn't find a
provisioning profile matching 'com.johncoates.camera'.

Code signing is required for product type 'Application' in SDK 'iOS 10.3'



Can you just send me pods_slate.framework ?

**Comment by JohnCoates** [comment]
Change your bundle ID in project settings

**Comment by JohnCoates** [comment]
You'll need to install CocoaPods https://cocoapods.org

When you run `pod install` it will generate that framework for you

**Comment by bloodmajik** [comment]
what should i change it to??

**Comment by JohnCoates** [comment]
Doesn't matter
com.bloodmajik.slate works

**Comment by bloodmajik** [comment]
off topic, but *maybe* you can help!

ld: framework not found Pods_slate

clang: error: linker command failed with exit code 1 (use -v to see
invocation)


I have the Pods-slate folder in my project. know why i get this error?

**Comment by JohnCoates** [comment]
Make sure you opened the workspace not the project, and make sure you ran
’pod install’

**Comment by bloodmajik** [comment]
ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see
invocation)



What can I do about that? If you need more log info let me know.

**Comment by JohnCoates** [comment]
Attach the full log

**Comment by bloodmajik** [comment]
https://hastebin.com/egifipozik.rb

**Comment by JohnCoates** [comment]
Weird stuff in that log. Are you trying to do something related to https://www.iskn.co/ ?

**Comment by bloodmajik** [comment]
Oh yea. like i said... off-topic. i emailed u think u were the creator of
the pods_slate framework

**Comment by JohnCoates** [comment]
lol, you didn't do a good job of clarifying that. pods_projectName is an automatically generated name for projects that use CocoaPods. The current issue you're getting is because the library you're using isn't compiled for the iOS simulator, only the device. So switch your target to a connected iOS device and you should be able to install and run
